[project]
name = "non-codeautomaticoperation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "firebase-admin>=7.4.0",
    "geographiclib>=2.1",
    "geopy>=2.4.1",
    "lxml>=6.1.0",
    "mediapipe>=0.10.35",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "psutil>=7.2.2",
    "pyautogui>=0.9.54",
    "pynput>=1.8.1",
    "pyopengl>=3.1.10",
    "pyopengl-accelerate>=3.1.10",
    "pyside6>=6.11.0",
    "pytesseract>=0.3.13",
    "pywinauto>=0.6.9",
]
